# Generated by Django 4.0.6 on 2022-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_category_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='energy_value',
            field=models.TextField(blank=True, verbose_name='Энергетичекская ценность'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время приготовления'),
        ),
    ]
